### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by lightwindcy** [Cyneburg/SDDSynergy#1]
Could you upload the DrugComb dataset,I checked your other repository and didn't find any

**Comment by Cyneburg** [comment]
https://drugcomb.org/download/

**Comment by Cyneburg** [comment]
You could download the DrugComb dataset from this url: https://drugcomb.org/download/

**Comment by lightwindcy** [comment]
thanks for your answer.Although I am not familiar with these data, I am trying to process them,I run your code on the Merck dataset you processed and only modified the data processing part. However, the experimental results of the five fold cross validation report showed that the AUC was only 0.93-0.94. Did I overlook anything?

**Comment by Cyneburg** [comment]
The experimental environment may affect the experimental results. In addition, the paper contains some data processing procedures in the results section, which you may have overlooked.
